# Generated by Django 4.2.16 on 2024-10-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
