# Generated by Django 5.1.2 on 2024-10-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_email_userprofile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
    ]
